// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
var aws_app_analytics = 'enable';
var aws_cognito_identity_pool_id = 'us-east-1:1413bcc3-873c-4df5-ab6e-92c02bc1256c';
var aws_cognito_region = 'us-east-1';
var aws_mobile_analytics_app_id = '9399cf227bf14b2090b307af258ab6b6';
var aws_mobile_analytics_app_region = 'us-east-1';
var aws_project_id = 'd1a1ffa6-7c88-4f8e-b33c-e9565e74936a';
var aws_project_name = 'RightOn';
var aws_project_region = 'us-east-1';
var aws_resource_name_prefix = 'righton-mobilehub-679705973';

AWS.config.region = aws_project_region;
AWS.config.credentials = new AWS.CognitoIdentityCredentials({
    IdentityPoolId: aws_cognito_identity_pool_id
  }, {
    region: aws_cognito_region
  });
AWS.config.update({customUserAgent: 'MobileHub v0.1'});
