projects:
  mobile:
    schemaPath: amplify/backend/api/mobile/build/schema.graphql
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
      - src/AWSMobileApi.ts
      - src/graphql/index.ts
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/AWSMobileApi.ts
        docsFilePath: src/graphql
        maxDepth: 8
  dev:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
extensions:
  amplify:
    version: 3
