# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number(xcodeproj: "RightOn.xcodeproj", skip_info_plist: true)
    build_app(workspace: "RightOn.xcworkspace", scheme: "RightOn")
    upload_to_testflight
    commit_version_bump
    # push_to_git_remote
  end
end
