export const timeSelection = [
  { label: 'No time limit', value: '0:00' },
  { label: '0:30', value: '0:30' },
  { label: '1:00', value: '1:00' },
  { label: '1:30', value: '1:30' },
  { label: '2:00', value: '2:00' },
  { label: '2:30', value: '2:30' },
  { label: '3:00', value: '3:00' },
  { label: '3:30', value: '3:30' },
  { label: '4:00', value: '4:00' },
  { label: '4:30', value: '4:30' },
  { label: '5:00', value: '5:00' },
  { label: '10:00', value: '10:00' },
  { label: '15:00', value: '15:00' },
  { label: '20:00', value: '20:00' },
  { label: '25:00', value: '25:00' },
  { label: '30:00', value: '30:00' },
  { label: '45:00', value: '45:00' },
  { label: '60:00', value: '60:00' },
];

export const categorySelection = [
  { label: 'Math', value: 'Math' },
  { label: 'Algebra', value: 'Algebra' },
  { label: 'Geometry', value: 'Geometry' },
  { label: 'Calculus', value: 'Calculus' },
  { label: 'Statistics', value: 'Statistics' },
  { label: 'Computer Science', value: 'Computer Science' },
  { label: 'Art', value: 'Art' },
  { label: 'Design', value: 'Design' },
  { label: 'Speech', value: 'Speech' },
  { label: 'Biology', value: 'Biology' },
  { label: 'Chemistry', value: 'Chemistry' },
  { label: 'Physics', value: 'Physics' },
  { label: 'Geography', value: 'Geography' },
  { label: 'Psychology', value: 'Psychology' },
  { label: 'History', value: 'History' },
  { label: 'Government', value: 'Government' },
  { label: 'Economics', value: 'Economics' },
  { label: 'English', value: 'English' },
  { label: 'Spanish', value: 'Spanish' },
  { label: 'French', value: 'French' },
  { label: 'German', value: 'German' },
  { label: 'Physical Education', value: 'Physical Education' },
];

export const levelSelection = [
  { label: 'Level 1', value: '1' },
  { label: 'Level 2', value: '2' },
  { label: 'Level 3', value: '3' },
  { label: 'Level 4', value: '4' },
  { label: 'Level 5', value: '5' },
  { label: 'Level 6', value: '6' },
  { label: 'Level 7', value: '7' },
  { label: 'Level 8', value: '8' },
];
