export const quizTimeSelection = [
  { label: 'No time limit', value: '0:00' },
  { label: '0:30', value: '0:30' },
  { label: '1:00', value: '1:00' },
  { label: '1:30', value: '1:30' },
  { label: '2:00', value: '2:00' },
  { label: '2:30', value: '2:30' },
  { label: '3:00', value: '3:00' },
  { label: '3:30', value: '3:30' },
  { label: '4:00', value: '4:00' },
  { label: '4:30', value: '4:30' },
  { label: '5:00', value: '5:00' },
];

export const trickTimeSelection = [
  { label: 'No time limit', value: '0:00' },
  { label: '2:00', value: '2:00' },
  { label: '2:30', value: '2:30' },
  { label: '3:00', value: '3:00' },
  { label: '3:30', value: '3:30' },
  { label: '4:00', value: '4:00' },
  { label: '4:30', value: '4:30' },
  { label: '5:00', value: '5:00' },
  { label: '10:00', value: '10:00' },
  { label: '15:00', value: '15:00' },
  { label: '20:00', value: '20:00' },
  { label: '25:00', value: '25:00' },
  { label: '30:00', value: '30:00' },
  { label: '45:00', value: '45:00' },
  { label: '60:00', value: '60:00' },
];

export const domainSelection = [
  { label: '[RP] - Ratios & Proportional Relationships', value: 'RP' },
  { label: '[NS] - The Number System', value: 'NS' },
  { label: '[EE] - Expressions & Equations', value: 'EE' },
  { label: '[G] - Geometry', value: 'G' },
  { label: '[SP] - Statistics & Probability', value: 'SP' },
  { label: '[F] - Functions', value: 'F' },
];

export const domainSelectionHS = [
  { label: 'Algebra I', value: 'section' },
  { label: '[HSN-Q] - Quantities', value: 'HSN-Q' },
  { label: '[HSA-CED] - Creating Equations', value: 'HSA-CED' },
  { label: '[HSA-REI] - Reasoning with Equations & Inequalities', value: 'HSA-REI' },
  { label: '[HSN-RN] - The Real Number System', value: 'HSN-RN' },
  { label: '[HSF-IF] - Interpreting Functions', value: 'HSF-IF' },
  { label: '[HSF-BF] - Building Functions', value: 'HSF-BF' },
  { label: '[HSF-LE] - Linear, Quadratic, & Exponential Models', value: 'HSF-LE' },
  { label: '[HSS-ID] - Interpreting Categorical & Quantitative Data', value: 'HSS-ID' },
  { label: '[HSA-SSE] - Seeing Structure in Expressions', value: 'HSA-SSE' },
  { label: '[HSA-APR] - Arithmetic with Polynomials & Rational Expressions', value: 'HSA-APR' },
  { label: 'Geometry', value: 'section' },
  { label: '[HSG-CO] - Congruence', value: 'HSG-CO' },
  { label: '[HSG-SRT] - Similarity, Right Triangles, & Trigonometry', value: 'HSG-SRT' },
  { label: '[HSG-MG] - Modeling with Geometry', value: 'HSG-MG' },
  { label: '[HSG-GMD] - Geometric Measurement & Dimension', value: 'HSG-GMD' },
  { label: '[HSG-GPE] - Expressing Geometric Properties with Equations', value: 'HSG-GPE' },
  { label: '[HSG-C] - Circles', value: 'HSG-C' },
  { label: '[HSS-CP] - Conditional Probability & the Rules of Probability', value: 'HSS-CP' },
  { label: '[HSS-MD] - Using Probability to Make Decisions', value: 'HSS-MD' },
  { label: 'Algebra II', value: 'section' },
  { label: '[HSN-CN] - The Complex Number System', value: 'HSN-CN' },
  { label: '[HSA-SSE] - Seeing Structure in Expressions', value: 'HSA-SSE' },
  { label: '[HSA-APR] - Arithmetic with Polynomials & Rational Expressions', value: 'HSA-APR' },
  { label: '[HSA-REI] - Reasoning with Equations & Inequalities', value: 'HSA-REI' },
  { label: '[HSF-TF] - Trigonometric Functions', value: 'HSF-TF' },
  { label: '[HSF-LE] - Linear, Quadratic, & Exponential Models', value: 'HSF-LE' },
  { label: '[HSS-ID] - Interpreting Categorical & Quantitative Data', value: 'HSS-ID' },
  { label: '[HSS-IC] - Making Inferences & Justifying Conclusions', value: 'HSS-IC' },
  { label: '[HSS-MD] - Using Probability to Make Decisions', value: 'HSS-MD' },
  { label: '[HSF-IF] - Interpreting Functions', value: 'HSF-IF' },
  { label: '[HSA-CED] - Creating Equations', value: 'HSA-CED' },
  { label: '[HSF-BF] - Building Functions', value: 'HSF-BF' },
  { label: 'Fourth Courses', value: 'section' },
  { label: '[HSN-CN] - The Complex Number System', value: 'HSN-CN' },
  { label: '[HSN-VM] - Vector & Matrix Quantities', value: 'HSN-VM' },
  { label: '[HSA-REI] - Reasoning with Equations & Inequalities', value: 'HSA-REI' },
  { label: '[HSF-IF] - Interpreting Functions', value: 'HSF-IF' },
  { label: '[HSF-BF] - Building Functions', value: 'HSF-BF' },
  { label: '[HSF-TF] - Trigonometric Functions', value: 'HSF-TF' },
  { label: '[HSG-GPE] - Expressing Geometric Properties with Equations', value: 'HSG-GPE' },
  { label: '[HSG-GMD] - Geometric Measurement & Dimension', value: 'HSG-GMD' },
  { label: '[HSS-MD] - Using Probability to Make Decisions', value: 'HSS-MD' },
];

export const gradeSelection = [
  { label: 'Grade 6', value: '6' },
  { label: 'Grade 7', value: '7' },
  { label: 'Grade 8', value: '8' },
  { label: 'High School', value: 'HS' },
  { label: 'General', value: 'General' },
];

export const clusterSelection = [
  { label: 'A', value: 'A' },
  { label: 'B', value: 'B' },
  { label: 'C', value: 'C' },
];

export const standardSelection = [
  { label: '1', value: '1' },
  { label: '2', value: '2' },
  { label: '3', value: '3' },
  { label: '4', value: '4' },
  { label: '5', value: '5' },
  { label: '6', value: '6' },
  { label: '7', value: '7' },
  { label: '8', value: '8' },
  { label: '9', value: '9' },
  { label: '10', value: '10' },
  { label: '11', value: '11' },
  { label: '12', value: '12' },
];
