/* eslint-disable */
// Placeholder Amplify config, committed on purpose.
//
// The real aws-exports.js is generated by the Amplify CLI (`amplify pull`) and is
// gitignored, because it differs per backend environment (main / dev / test) and is
// machine-written. See CONTRIBUTING.md.
//
// This file exists so CI can COMPILE the apps without AWS credentials. The values are
// deliberately fake. `Amplify.configure()` runs at runtime, not build time, so webpack
// only needs this module to exist and export the expected shape.
//
// Do NOT deploy a bundle built against this file — it cannot reach any backend.
// The deploy pipeline runs `amplify pull --envName <env>` to write the real config first.

const awsmobile = {
  aws_project_region: 'us-east-1',
  aws_appsync_graphqlEndpoint:
    'https://example00000000000000000000.appsync-api.us-east-1.amazonaws.com/graphql',
  aws_appsync_region: 'us-east-1',
  aws_appsync_authenticationType: 'AWS_IAM',
  aws_appsync_apiKey: 'da2-000000000000000000000000',
  aws_cognito_identity_pool_id: 'us-east-1:00000000-0000-0000-0000-000000000000',
  aws_cognito_region: 'us-east-1',
  aws_user_pools_id: 'us-east-1_EXAMPLE00',
  aws_user_pools_web_client_id: '0000000000000000000000000',
  oauth: {
    domain: 'example-example-dev.auth.us-east-1.amazoncognito.com',
    scope: ['email', 'openid', 'profile', 'aws.cognito.signin.user.admin'],
    redirectSignIn: 'http://localhost:3000/',
    redirectSignOut: 'http://localhost:3000/',
    responseType: 'code',
  },
  federationTarget: 'COGNITO_USER_POOLS',
  aws_cognito_username_attributes: [],
  aws_cognito_social_providers: ['GOOGLE'],
  aws_cognito_signup_attributes: ['EMAIL'],
  aws_cognito_mfa_configuration: 'OFF',
  aws_cognito_mfa_types: ['SMS'],
  aws_cognito_password_protection_settings: {
    passwordPolicyMinLength: 8,
    passwordPolicyCharacters: [],
  },
  aws_cognito_verification_mechanisms: ['EMAIL'],
  aws_user_files_s3_bucket: 'example-storage-bucket',
  aws_user_files_s3_bucket_region: 'us-east-1',
};

export default awsmobile;
