/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: "us-east-1",
  aws_appsync_graphqlEndpoint:
    "https://kgqgejrwenhxtbout2fal7cc6i.appsync-api.us-east-1.amazonaws.com/graphql",
  aws_appsync_region: "us-east-1",
  aws_appsync_authenticationType: "API_KEY",
  aws_appsync_apiKey: "da2-m73kyxxpbbdahiajhq3gm4o6ni",
  aws_cognito_region: "us-east-1",
  aws_user_pools_id: "us-east-1_cC3q3fBKW",
  aws_user_pools_web_client_id: "1qi0l2sm7hr82ou1mqsv4tc1ff",
  oauth: {
    domain: "rightoneducation.auth.us-east-1.amazoncognito.com",
  },
  aws_cognito_username_attributes: [],
  aws_cognito_social_providers: [],
  aws_cognito_signup_attributes: ["EMAIL"],
  aws_cognito_mfa_configuration: "OFF",
  aws_cognito_mfa_types: [],
  aws_cognito_password_protection_settings: {
    passwordPolicyMinLength: 8,
    passwordPolicyCharacters: ["REQUIRES_NUMBERS"],
  },
  aws_cognito_verification_mechanisms: ["EMAIL"],
};

export default awsmobile;
