// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_cognito_identity_pool_id': 'us-east-2:c187d84b-9641-4fd1-8f99-e9679f388122',
    'aws_cognito_region': 'us-east-2',
    'aws_project_id': 'e166c9b9-6873-4c86-9eea-dae956e7586b',
    'aws_project_name': 'RightOn',
    'aws_project_region': 'us-east-2',
    'aws_resource_name_prefix': 'righton-mobilehub-503791219',
    'aws_sign_in_enabled': 'enable',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'us-east-2_qlqgzWiEP',
    'aws_user_pools_mfa_type': 'OFF',
    'aws_user_pools_web_client_id': '5e3inlsnf407elne8ee01qcnri',
}

export default awsmobile;
