<<<<<<< HEAD
const awsmobile = {
  "aws_project_region": "us-east-1",
  "aws_appsync_graphqlEndpoint": "https://rtta7pxyhrdwrlg3d2vrw2mdri.appsync-api.us-east-1.amazonaws.com/graphql",
  "aws_appsync_region": "us-east-1",
  "aws_appsync_authenticationType": "API_KEY",
  "aws_appsync_apiKey": "da2-bnjdiewpkjh2dl7y7dyz4kn7bu",
  "aws_user_pools_id": "us-east-1_cC3q3fBKW",
  "aws_user_pools_web_client_id": "1qi0l2sm7hr82ou1mqsv4tc1ff",
=======
/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://rtta7pxyhrdwrlg3d2vrw2mdri.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-bnjdiewpkjh2dl7y7dyz4kn7bu"
>>>>>>> a5965acc48bb423681b99f6268caf083ccb85864
};


export default awsmobile;
