// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
  aws_app_analytics: 'enable',
  aws_cognito_identity_pool_id: 'us-east-2:a5113eb1-8aba-4d1b-aa87-2e975e37533d',
  aws_cognito_region: 'us-east-2',
  aws_content_delivery: 'enable',
  aws_content_delivery_bucket: 'righton-hosting-mobilehub-1165632669',
  aws_content_delivery_bucket_region: 'us-east-2',
  aws_content_delivery_cloudfront: 'enable',
  aws_content_delivery_cloudfront_domain: 'd21j6wbpdnf7o4.cloudfront.net',
  aws_mobile_analytics_app_id: 'a9a84ba86a3b4f6c9a4fd1dd9c2e44c1',
  aws_mobile_analytics_app_region: 'us-east-1',
  aws_project_id: '81157d78-ab5e-478e-a49d-99e18828c3e4',
  aws_project_name: 'RightOn',
  aws_project_region: 'us-east-2',
  aws_resource_name_prefix: 'righton-mobilehub-1165632669',
};

export default awsmobile;
