// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:b4625dc0-227e-4872-a0f0-3095d4f1ef27",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_oVDoZFvFM",
    "aws_user_pools_web_client_id": "4uushlqpafqjl3t5cg5vjpkvtp",
    "aws_dynamodb_all_tables_region": "us-east-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "GameRooms",
            "region": "us-east-1"
        }
    ],
    "aws_cloud_logic_custom": [
        {
            "name": "TeacherGameAPI",
            "endpoint": "https://hh6pg9sfh9.execute-api.us-east-1.amazonaws.com/Prod",
            "region": "us-east-1"
        }
    ]
};


export default awsmobile;
